### ISSUE TITLE
[UI] StringIndexOutOfBoundsException in ViewContextUpdateSecurity:splitParamName

### ISSUE THREAD

**Issue by skerdudou** [vertigo-io/vertigo-libs#71]
When checking for `isAllowedField` in `ViewContextUpdateSecurity`, if the `paramName` target a simple field that is not allowed, we try to split as if it is an object and get a `StringIndexOutOfBoundsException` in the `splitParamName` method.

Example :
- allowedFields = ["vContext[aaa]"]
- paramName = "vContext[bbb]"

**Comment by skerdudou** [comment]
In some cases I have POSTs with `vContext['aaa']` (with quotes) in my custom code. Should it be an accepted format ?
In the meanwhile, I delete thoses quotes.

**Comment by NPi2Loup** [comment]
Fixed by [#105f00](https://github.com/vertigo-io/vertigo-extensions/commit/105f00f84effd7dffa4b7fde0af00f49966ae0ca)
-> v3.4.0
